### ISSUE TITLE
Strange behavior on pages

### ISSUE THREAD

**Issue by 73VW** [sitn/ne-mobilite2030#2]
As you can see in the following picture
![image](https://user-images.githubusercontent.com/24651698/47565578-4045c180-d929-11e8-98d7-85adecc327a6.png)
I wonder if this is normal to see a part of the map `div` directly in the overlay part.

Same happens for vision page with first and second sections:
![image](https://user-images.githubusercontent.com/24651698/47565628-6ff4c980-d929-11e8-9067-3d62353735e4.png)

And almost all the other pages.

**Comment by kalbermattenm** [comment]
Hmmm... We did not design the application. This was done by an external company. I think that the purpose of this red map was to show the transports links of Neuchâtel and they used it as some kind of a header in some pages, so I am quite disconcerted about what to answer exactly...

**Comment by 73VW** [comment]
Well in fact I am not talking about the map that overlaps the next section but that the second section can be seen even when you are at the top of the scroll.
Here are a full screenshots;
![image](https://user-images.githubusercontent.com/24651698/47578590-0c2ec880-d94a-11e8-86ce-695365536585.png)
![image](https://user-images.githubusercontent.com/24651698/47578608-18b32100-d94a-11e8-8e15-1fd18d793779.png)

I just wanted to tell you that the layout might not work as expected (Maybe some changes in browsers interpretation of css or something else that changed since the site was published). I wasn't especially expecting an answer to this.

I wish you a nice weekend.
